winzou_state_machine:
    ekyna_payment:
        class:         Ekyna\Component\Sale\Payment\PaymentInterface
        property_path: state
        state_machine_class: Ekyna\Bundle\PaymentBundle\StateMachine\StateMachine
        states:
            new:        ~
            pending:    ~
            processing: ~
            cancelled:  ~
            failed:     ~
            authorized: ~
            completed:  ~
            refunded:   ~
            unknown:    ~
            void:       ~
        transitions:
            create:
                from: [new]
                to:   pending
            process:
                from: [new, pending]
                to:   processing
            cancel:
                from: [new, pending, processing]
                to:   cancelled
            fail:
                from: [new, pending, processing]
                to:   failed
            authorize:
                from: [new, pending, processing]
                to:   authorized
            complete:
                from: [new, pending, processing, authorized]
                to:   completed
            refund:
                from: [completed]
                to:   refunded
            void:
                from: [new, pending]
                to:   void
